# Generated by Django 2.2.5 on 2019-09-28 07:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0002_auto_20190927_2220'),
        ('tasks', '0002_auto_20190928_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='typetype',
        ),
        migrations.AddField(
            model_name='task',
            name='checker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='checker.Checker'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='finishDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 28, 7, 51, 3, 973936, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contest',
            name='startDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 28, 7, 51, 3, 973892, tzinfo=utc)),
        ),
    ]
