# Generated by Django 2.2.5 on 2019-11-10 08:12

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20191109_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='judgerComment',
        ),
        migrations.AlterField(
            model_name='contest',
            name='finishDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 10, 8, 12, 27, 609590, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contest',
            name='startDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 10, 8, 12, 27, 609553, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='solution',
            name='description',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2000), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='solution',
            name='submitTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 10, 8, 12, 27, 608519, tzinfo=utc)),
        ),
    ]
