# Generated by Django 2.2.5 on 2019-09-29 11:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20190929_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='general_name',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='hardness',
        ),
        migrations.AlterField(
            model_name='contest',
            name='finishDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 29, 11, 30, 30, 394688, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contest',
            name='startDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 29, 11, 30, 30, 394625, tzinfo=utc)),
        ),
    ]
