# Generated by Django 2.2.5 on 2019-09-29 11:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django_enumfield.db.fields
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20190929_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='general_name',
            field=models.CharField(default='Геометрия', max_length=200),
        ),
        migrations.AddField(
            model_name='theme',
            name='hardness',
            field=django_enumfield.db.fields.EnumField(default=2, enum=tasks.models.Hardness),
        ),
        migrations.AlterField(
            model_name='contest',
            name='finishDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 29, 11, 30, 49, 418391, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contest',
            name='startDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 29, 11, 30, 49, 418343, tzinfo=utc)),
        ),
    ]
