# Generated by Django 2.2.5 on 2019-11-10 10:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20191110_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='finishDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 10, 10, 13, 42, 951849, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contest',
            name='startDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 10, 10, 13, 42, 951821, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='solution',
            name='submitTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 10, 10, 13, 42, 951041, tzinfo=utc)),
        ),
    ]
