# Generated by Django 2.2.5 on 2019-09-29 15:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import enumfields.fields
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20190929_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcase',
            name='level',
        ),
        migrations.AddField(
            model_name='taskcase',
            name='hardness',
            field=enumfields.fields.EnumField(default='MIDDLE', enum=tasks.models.Hardness, max_length=500),
        ),
        migrations.AlterField(
            model_name='contest',
            name='finishDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 29, 15, 28, 48, 205742, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contest',
            name='startDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 29, 15, 28, 48, 205689, tzinfo=utc)),
        ),
    ]
