# Generated by Django 2.2.5 on 2019-09-30 16:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20190929_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='submitTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 30, 16, 38, 44, 382834, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contest',
            name='finishDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 30, 16, 38, 44, 383711, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contest',
            name='startDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 30, 16, 38, 44, 383676, tzinfo=utc)),
        ),
    ]
