# Generated by Django 2.2.5 on 2019-10-01 17:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_auto_20190930_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='judgerComment',
            field=models.CharField(default='', max_length=20000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contest',
            name='finishDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 1, 17, 11, 32, 492096, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contest',
            name='startDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 1, 17, 11, 32, 492052, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='solution',
            name='submitTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 1, 17, 11, 32, 490936, tzinfo=utc)),
        ),
    ]
