# Generated by Django 2.1.2 on 2019-02-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000)),
                ('author', models.CharField(max_length=100)),
                ('type', models.IntegerField()),
            ],
        ),
    ]
