# Generated by Django 2.1.2 on 2019-02-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='right_answer',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
