# Generated by Django 2.1.5 on 2019-02-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_right_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=2000)),
                ('isRight', models.BooleanField()),
            ],
        ),
    ]
