# Generated by Django 2.1.5 on 2019-02-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_solves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solves',
            name='isRight',
            field=models.BooleanField(null=True),
        ),
    ]
