# Generated by Django 2.1.5 on 2019-02-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20190218_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='solves',
            name='task_id',
            field=models.IntegerField(default=0),
        ),
    ]
