# Generated by Django 2.1.5 on 2019-02-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_solves_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='Task', max_length=200),
        ),
    ]
