# Generated by Django 2.1.5 on 2019-03-02 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_task_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='type',
            new_name='typetype',
        ),
    ]
