# Generated by Django 2.2.5 on 2019-09-22 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_auto_20190922_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='theme',
        ),
    ]
