# Generated by Django 2.2.5 on 2019-09-22 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_remove_task_theme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
