# Generated by Django 2.2.5 on 2019-09-22 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_theme'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Solves',
            new_name='Solution',
        ),
        migrations.AlterModelOptions(
            name='solution',
            options={'verbose_name': 'Solution', 'verbose_name_plural': 'Solutions'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
    ]
