# Generated by Django 2.2.5 on 2019-09-22 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_auto_20190922_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='theme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='task.Theme'),
        ),
    ]
