# Generated by Django 2.2.5 on 2019-09-22 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_task_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='theme',
        ),
    ]
