# Generated by Django 2.2.5 on 2019-09-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_remove_task_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='tasks',
            field=models.ManyToManyField(to='task.Task'),
        ),
    ]
