# Generated by Django 2.2.5 on 2019-09-22 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0016_taskcase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='tasks',
        ),
    ]
