# Generated by Django 2.2.5 on 2019-09-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0017_remove_theme_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='tasks',
            field=models.ManyToManyField(through='task.TaskCase', to='task.Task'),
        ),
    ]
