# Generated by Django 2.2.5 on 2019-11-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='link',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
