# Generated by Django 2.2.5 on 2019-10-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_auto_20191003_2246'),
        ('userprofile', '0003_auto_20191003_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rang',
            field=models.ManyToManyField(to='tasks.Theme'),
        ),
    ]
