# Generated by Django 2.2.5 on 2019-10-03 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_auto_20191003_2313'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0004_profile_rang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rang',
        ),
        migrations.AlterField(
            model_name='profile',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Rang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rang', models.FloatField()),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Theme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
