# Generated by Django 2.2.5 on 2019-10-03 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_auto_20191003_2321'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0005_auto_20191003_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rang',
            name='rang',
        ),
        migrations.RemoveField(
            model_name='rang',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='rang',
            name='user',
        ),
        migrations.AddField(
            model_name='rang',
            name='name',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.CreateModel(
            name='UserRang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Rang')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Theme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
