# Generated by Django 2.1.2 on 2019-02-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='author',
            field=models.CharField(default='People', max_length=100),
        ),
        migrations.AddField(
            model_name='contest',
            name='team_size',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='contest',
            name='duraction',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='contest',
            name='task_1_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='contest',
            name='task_2_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='contest',
            name='task_3_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='contest',
            name='task_4_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='contest',
            name='task_5_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='contest',
            name='task_6_id',
            field=models.IntegerField(default=-1),
        ),
    ]
