# Generated by Django 2.1.5 on 2019-02-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest_page', '0002_auto_20190217_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='isStarted',
            field=models.BooleanField(default=False),
        ),
    ]
