# Generated by Django 2.1.5 on 2019-02-19 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest_page', '0003_contest_isstarted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='isStarted',
        ),
    ]
