# Generated by Django 2.1.5 on 2019-02-19 12:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contest_page', '0004_remove_contest_isstarted'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='dateED',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 19, 12, 0, 40, 61658, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='contest',
            name='dateST',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 19, 12, 0, 40, 61592, tzinfo=utc)),
        ),
    ]
