# Generated by Django 2.1.2 on 2019-02-28 09:02

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contest_page', '0005_auto_20190219_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='duraction',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='task_1_id',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='task_2_id',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='task_3_id',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='task_4_id',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='task_5_id',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='task_6_id',
        ),
        migrations.AddField(
            model_name='contest',
            name='tasks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[], size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contest',
            name='dateED',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 28, 9, 2, 32, 511910, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contest',
            name='dateST',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 28, 9, 2, 32, 511778, tzinfo=utc)),
        ),
    ]
