# Generated by Django 2.1.2 on 2019-02-28 09:06

import contest_page.models
import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contest_page', '0008_auto_20190228_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='dateED',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 28, 9, 6, 4, 396206, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contest',
            name='dateST',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 28, 9, 6, 4, 396090, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contest',
            name='tasks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=contest_page.models.Contest.task_default, size=None),
        ),
    ]
