# Generated by Django 2.1.2 on 2019-02-28 09:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contest_page', '0010_auto_20190228_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='dateED',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 28, 9, 18, 23, 859808, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contest',
            name='dateST',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 28, 9, 18, 23, 859763, tzinfo=utc)),
        ),
    ]
