# Generated by Django 2.1.2 on 2019-02-28 09:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contest_page', '0011_auto_20190228_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='dateED',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 28, 9, 24, 48, 717937, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contest',
            name='dateST',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 28, 9, 24, 48, 717890, tzinfo=utc)),
        ),
    ]
