# Generated by Django 2.1.5 on 2019-03-02 09:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contest_page', '0012_auto_20190228_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='dateED',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 2, 9, 4, 50, 818956, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contest',
            name='dateST',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 2, 9, 4, 50, 818913, tzinfo=utc)),
        ),
    ]
