# Generated by Django 2.1.5 on 2019-03-02 09:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_auto_20190302_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2019, 3, 2, 9, 10, 35, 144450, tzinfo=utc)),
        ),
    ]
