from enumfields import Enum

class Virdict(Enum):
	WRONG_ANSWER = 'WRONG_ANSWER'
	ACCEPTED_FOR_EVUALETION = 'ACCEPTED_FOR_EVUALETION'
	IN_EVUALETION = 'IN_EVUALETION'
	REJECTED = 'REJECTED'
	ACCEPTED = 'ACCEPTED'
	ACCEPTED_FOR_EVUALETION_IN_CONTEST = 'ACCEPTED_FOR_EVUALETION_IN_CONTEST'

