# Generated by Django 2.2.5 on 2019-09-27 19:12

from django.db import migrations, models
import python_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', python_field.fields.PythonCodeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Checker',
                'verbose_name_plural': 'Checkers',
            },
        ),
    ]
