# Generated by Django 2.2.5 on 2019-10-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.FileField(upload_to='uploads/checkers')),
            ],
            options={
                'verbose_name': 'Checker',
                'verbose_name_plural': 'Checkers',
            },
        ),
    ]
